clip_arch: 'ViT-B-32'
clip_path: clip_laion2b_s34b_b79k
clip_visual_dim: 768
clip_text_dim: 512
state_num: 3
num_actions: 8
action_bins: 256
scene_transformer_depth: 6
action_transformer_depth: 3
embed_dim: 512
dropout: 0.1